config/routes.rb
Rails.application.routes.draw do

  root to: 'stories#index'

  resources :stories, only: :index
  get 'stories/older' => 'stories#older'

end

app/models/story.rb
class Story
  attr_reader :headline, :byline, :url, :summary, :image, :last_published

  IMAGE_URL = 'https://graphics8.nytimes.com/'

  def initialize(opts={})
    @headline = opts[:headline]
    @byline = opts[:byline]
    @url = opts[:url]
    @summary = opts[:summary]
    @image = opts[:image]
    @last_published = opts[:last_published]
  end

  def publish_date
    last_published.to_time.strftime("%-m/%-d/%Y")
  end

  def image_url
    if image.empty?
      ''
    else
      URI.join(IMAGE_URL, image[0]['types'][0]['content'])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :filter_request

  private

  def filter_request
    if !request.get?
      render status: 403, body: 'forbidden request'
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @full_stories, @other_stories = stories.partition do |story|
      story.image.present?
    end
  rescue
    render :error
  end

  private

  def stories
    GetStories.call
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper

  def language
    if martian?
      'English'
    else
      'Martian'
    end
  end

  def toggleable_text(text)
    if martian?
      to_martian(text)
    else
      text
    end
  end

  private

  def to_martian(text)
    text.gsub(/[\w']{4,}/i) do |word|
      if word[0].match(/[[:upper:]]/)
        'Boinga'
      else
        'boinga'
      end
    end
  end

  def martian?
    params[:language] == 'Martian'
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title NytApp
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/stories/error.html.haml
#wrapper
  #main
    %h1.page-title Oops! Something went wrong!
    .row
      .col-12
        %p.error Please refresh the page or come back later.

app/views/stories/index.html.haml
#wrapper
  %header
    .nav
      %ul.topnav
        %li= link_to language, stories_path(language: language)

  #main
    %h1.page-title Today's Stories
    .row
      .col-10
        - @full_stories.each_slice(2) do |stories|
          .row.full-stories
            - stories.each do |story|
              .col-6.col-m-6
                %p.headline
                  = link_to(toggleable_text(story.headline), story.url)
                %p.byline
                  = story.byline
                %p.last-published
                  = story.publish_date
                .row.story-info
                  .col-5
                    = image_tag(story.image_url)
                  .col-7
                    %p.summary
                      = toggleable_text(story.summary)
      .col-2
        - @other_stories.each do |story|
          .row.stories-without-images
            %ul
              %li.headline= link_to(toggleable_text(story.headline), story.url)
              %li.byline= story.byline
              %li.last-published= story.publish_date
              %li.side-summary= toggleable_text(story.summary)
  .row
    .col-12
      = link_to 'Older stories', '#', remote: true, id: 'olderStories', class: 'older-stories'